package geral;

import Buscas.*;
import Cadastros.*;
import POJOs.*;
import DAOs.*;
import javax.swing.JFrame;
import java.util.ArrayList;

/**
 *
 * @author Augusto
 */
public class Menu extends javax.swing.JFrame {
    
    public String usuario = "";
    
    /**
     * Creates new form Hospital
     */
    public Menu() {
        initComponents();
        
        this.usuarioAtualLabel.setVisible(false);
        this.usuarioAtual.setVisible(false);
        this.barraMenu.setVisible(false);
    }
    
    public Menu(String usuario) {
        initComponents();
        
        this.usuarioAtualLabel.setVisible(true);
        this.usuarioAtual.setText(usuario);
        this.usuario = usuario;
        this.botaoLogin.setText("Logout");
    }
    
    public void abreTabela(int tipo){
        switch(tipo){
            case 0 -> this.menuListaPacientes.doClick();
            case 1 -> this.menuListaMedicos.doClick();
            case 2 -> this.menuListaConsultas.doClick();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        usuarioAtual = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        usuarioAtualLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuPaciente = new javax.swing.JMenu();
        menuBuscaPaciente = new javax.swing.JMenuItem();
        menuListaPacientes = new javax.swing.JMenuItem();
        menuNovoPaciente = new javax.swing.JMenuItem();
        menuMedico = new javax.swing.JMenu();
        menuBuscaMedico = new javax.swing.JMenuItem();
        menuListaMedicos = new javax.swing.JMenuItem();
        menuNovoMedico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuChecarConsulta = new javax.swing.JMenuItem();
        menuListaConsultas = new javax.swing.JMenuItem();
        menuNovaConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 102)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro Médico Online");

        botaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLogin.setText("Fazer Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        usuarioAtual.setForeground(new java.awt.Color(255, 255, 255));
        usuarioAtual.setText("Nome");

        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        usuarioAtualLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioAtualLabel.setForeground(new java.awt.Color(255, 255, 255));
        usuarioAtualLabel.setText("Usuário Atual:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconDoctor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usuarioAtualLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtualLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        menuPaciente.setText("Paciente");
        menuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacienteActionPerformed(evt);
            }
        });

        menuBuscaPaciente.setText("Buscar Paciente");
        menuBuscaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaPacienteActionPerformed(evt);
            }
        });
        menuPaciente.add(menuBuscaPaciente);

        menuListaPacientes.setText("Listar Pacientes");
        menuListaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaPacientesActionPerformed(evt);
            }
        });
        menuPaciente.add(menuListaPacientes);

        menuNovoPaciente.setText("Novo Paciente");
        menuNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoPacienteActionPerformed(evt);
            }
        });
        menuPaciente.add(menuNovoPaciente);

        barraMenu.add(menuPaciente);

        menuMedico.setText("Médico");

        menuBuscaMedico.setText("Buscar Médico");
        menuBuscaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaMedicoActionPerformed(evt);
            }
        });
        menuMedico.add(menuBuscaMedico);

        menuListaMedicos.setText("Listar Médicos");
        menuListaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaMedicosActionPerformed(evt);
            }
        });
        menuMedico.add(menuListaMedicos);

        menuNovoMedico.setText("Novo Médico");
        menuNovoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoMedicoActionPerformed(evt);
            }
        });
        menuMedico.add(menuNovoMedico);

        barraMenu.add(menuMedico);

        jMenu1.setText("Consultas e Exames");

        menuChecarConsulta.setText("Buscar Consulta");
        menuChecarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChecarConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(menuChecarConsulta);

        menuListaConsultas.setText("Listar Consultas");
        menuListaConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(menuListaConsultas);

        menuNovaConsulta.setText("Nova Consulta");
        menuNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(menuNovaConsulta);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuListaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaPacientesActionPerformed
        Tabela tabela = new Tabela(this, "Pacientes");
        DAOPaciente daoPaciente = new DAOPaciente();
        ArrayList<Paciente> listaPacientes = daoPaciente.selecionarTodosRegistros();
        
        for(Paciente p : listaPacientes){
            tabela.adicionaLinha(p.toArrayObjects());
        }
        
        tabela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuListaPacientesActionPerformed

    private void menuListaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaMedicosActionPerformed
        Tabela tabela = new Tabela(this, "Medicos");
        DAOMedico daoMedico = new DAOMedico();
        ArrayList<Medico> listaMedicos = daoMedico.selecionarTodosRegistros();
        
        for(Medico m : listaMedicos){
            tabela.adicionaLinha(m.toArrayObjects());
        }
        tabela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuListaMedicosActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        this.dispose();
        if(this.usuario.isEmpty()){
            new TelaLogin().setVisible(true);
        }else{
            new Menu().setVisible(true);
        }
        
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void menuNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoPacienteActionPerformed
        this.setVisible(false);
        new CadastroPaciente(this).setVisible(true);
    }//GEN-LAST:event_menuNovoPacienteActionPerformed

    private void menuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPacienteActionPerformed

    private void menuBuscaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaPacienteActionPerformed
        this.setVisible(false);
        new BuscaPaciente(this).setVisible(true);
    }//GEN-LAST:event_menuBuscaPacienteActionPerformed

    private void menuNovoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoMedicoActionPerformed
        this.setVisible(false);
        new CadastroMedico(this).setVisible(true);
    }//GEN-LAST:event_menuNovoMedicoActionPerformed

    private void menuBuscaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaMedicoActionPerformed
        this.setVisible(false);
        new BuscaMedico(this).setVisible(true);
    }//GEN-LAST:event_menuBuscaMedicoActionPerformed

    private void menuNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaConsultaActionPerformed
        this.setVisible(false);
        new CadastroConsulta(this).setVisible(true);
    }//GEN-LAST:event_menuNovaConsultaActionPerformed

    private void menuListaConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaConsultasActionPerformed
        Tabela tabela = new Tabela(this, "Consultas");
        DAOConsulta daoConsulta = new DAOConsulta();
        ArrayList<Consulta> listaConsultas = daoConsulta.selecionarTodosRegistros();
        
        for(Consulta c : listaConsultas){
            tabela.adicionaLinha(c.toArrayObjects());
        }
        
        tabela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuListaConsultasActionPerformed

    private void menuChecarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChecarConsultaActionPerformed
        this.setVisible(false);
        new BuscaConsulta(this).setVisible(true);
    }//GEN-LAST:event_menuChecarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuBuscaMedico;
    private javax.swing.JMenuItem menuBuscaPaciente;
    private javax.swing.JMenuItem menuChecarConsulta;
    private javax.swing.JMenuItem menuListaConsultas;
    private javax.swing.JMenuItem menuListaMedicos;
    private javax.swing.JMenuItem menuListaPacientes;
    private javax.swing.JMenu menuMedico;
    private javax.swing.JMenuItem menuNovaConsulta;
    private javax.swing.JMenuItem menuNovoMedico;
    private javax.swing.JMenuItem menuNovoPaciente;
    private javax.swing.JMenu menuPaciente;
    private javax.swing.JLabel usuarioAtual;
    private javax.swing.JLabel usuarioAtualLabel;
    // End of variables declaration//GEN-END:variables
}
